(function(){
 const $=id=>document.getElementById(id), escText=(v)=>v==null?'':String(v), mask=(v)=>{const s=String(v||'');return s.length<=4?'••••':'••••'+s.slice(-4)};
 let page=0,search='';const PAGE=50;let cache={tasks:[],events:[]};
 function status(text,kind='status'){const e=$('adminStatus');if(e){e.textContent=text;e.className=kind}}
 function cell(v){const td=document.createElement('td');td.textContent=escText(v);return td}
 function button(text,attrs={}){const b=document.createElement('button');b.className='btn secondary';b.type='button';b.textContent=text;Object.entries(attrs).forEach(([k,v])=>b.dataset[k]=v);return b}
 function table(headers,rows){const wrap=document.createElement('div');wrap.className='table-wrap';const t=document.createElement('table');t.className='table';const thead=document.createElement('thead'),tr=document.createElement('tr');headers.forEach(h=>{const th=document.createElement('th');th.textContent=h;tr.appendChild(th)});thead.appendChild(tr);t.appendChild(thead);const tb=document.createElement('tbody');rows.forEach(r=>tb.appendChild(r));t.appendChild(tb);wrap.appendChild(t);return wrap}
 async function guard(){const sb=window.pakcashSupabase;if(!sb){status('Supabase configuration is unavailable.','error');return false}const s=await window.pakcashGetSession();if(!s){location.replace('/login.html');return false}const {data,error}=await sb.rpc('is_admin');if(error||!data){status('Admin access denied.','error');return false}$('adminUI').classList.remove('hidden');$('guard').classList.add('hidden');return true}
 async function load(){const sb=window.pakcashSupabase;status('Loading admin data…');try{
  const from=Math.max(0,page*PAGE),to=from+PAGE-1;
  let usersQ=sb.from('profiles').select('id,username,verified_referrals,account_status,created_at',{count:'exact'}).order('created_at',{ascending:false}).range(from,to);if(search)usersQ=usersQ.ilike('username','%'+search.replace(/[%_]/g,'')+'%');
  const [u,w,r,ev,ta,a,paid,pendingExact]=await Promise.all([usersQ,sb.from('withdrawals').select('id,user_id,amount_pkr,method,destination,status,created_at,reviewed_at,approved_at,rejected_at,paid_at,refunded_at,payment_reference,admin_notes').in('status',['pending','approved','rejected']).order('created_at',{ascending:false}).limit(100),sb.from('referrals').select('id,referrer_id,referred_id,referral_code,status,created_at').eq('status','pending').order('created_at').limit(100),sb.from('events').select('*').order('id'),sb.from('tasks').select('*').order('id'),sb.from('audit_logs').select('id,action,target_type,target_id,created_at,actor_user_id,metadata').order('created_at',{ascending:false}).limit(50),sb.from('withdrawals').select('id',{count:'exact',head:true}).eq('status','paid'),sb.from('withdrawals').select('id',{count:'exact',head:true}).eq('status','pending')]);
  if(u.error)throw u.error; const userIds=(u.data||[]).map(x=>x.id);const wallets=userIds.length?(await sb.from('wallets').select('user_id,balance_pkr,reserved_pkr,total_earned_pkr').in('user_id',userIds)).data||[]:[];const wm=new Map(wallets.map(x=>[x.user_id,x]));
  $('usersCount').textContent=String(u.count??u.data?.length??0);$('pendingCount').textContent=String(pendingExact.count??0);$('paidCount').textContent=String(paid.count??0);cache.tasks=ta.data||[];cache.events=ev.data||[];
  renderWithdrawals(w.data||[]);renderReferrals(r.data||[]);renderUsers(u.data||[],wm);renderTasks(cache.tasks);renderEvents(cache.events);renderAudit(a.data||[]);status('Admin data loaded.','success');
 }catch(e){status('Admin data could not be loaded. Please retry.','error')}}
 function renderWithdrawals(rows){const box=$('withdrawals');box.textContent='';if(!rows.length){box.className='empty';box.textContent='No open/reviewed withdrawal records in this queue.';return}box.className='';rows.forEach(x=>{const article=document.createElement('article');article.className='task';const left=document.createElement('div'),strong=document.createElement('strong'),p=document.createElement('p');strong.textContent='#'+x.id+' · ₨'+Number(x.amount_pkr).toFixed(2);p.textContent=x.status+' · '+x.method+' · destination '+mask(x.destination)+' · user '+x.user_id;left.append(strong,p);const actions=document.createElement('div');actions.className='actions';if(x.status==='pending'){actions.append(button('Approve',{'approve':x.id}),button('Reject',{'reject':x.id}))}else if(x.status==='approved'){actions.append(button('Mark paid',{'paid':x.id}),button('Reject',{'reject':x.id}))}else if(x.status==='rejected'){actions.append(button('Refund',{'refund':x.id}))}article.append(left,actions);box.appendChild(article)})}
 function renderReferrals(rows){const box=$('referrals');box.textContent='';if(!rows.length){box.className='empty';box.textContent='No pending referrals.';return}box.className='';rows.forEach(x=>{const a=document.createElement('article');a.className='task';const d=document.createElement('div');const s=document.createElement('strong');s.textContent='#'+x.id;const p=document.createElement('p');p.textContent='Referrer '+x.referrer_id+' · Referred '+x.referred_id;d.append(s,p);a.append(d,button('Verify',{'ref':x.id}));box.appendChild(a)})}
 function renderUsers(rows,wm){const box=$('users');box.textContent='';const rs=rows.map(x=>{const tr=document.createElement('tr');tr.append(cell(x.username),cell(x.account_status),cell(x.verified_referrals),cell('₨'+Number(wm.get(x.id)?.balance_pkr||0).toFixed(2)),cell('₨'+Number(wm.get(x.id)?.reserved_pkr||0).toFixed(2)));const td=document.createElement('td'),sel=document.createElement('select');sel.dataset.statusUser=x.id;['active','suspended','closed'].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;o.selected=v===x.account_status;sel.appendChild(o)});const b=button('Save',{'statusSave':x.id});td.append(sel,b);tr.append(td,cell(x.id));return tr});box.appendChild(table(['Username','Status','Verified refs','Available','Reserved','Change status','User ID'],rs));const pager=document.createElement('div');pager.className='actions';const prev=button('Previous');prev.disabled=page===0;prev.addEventListener('click',()=>{page--;load()});const next=button('Next');next.disabled=rows.length<PAGE;next.addEventListener('click',()=>{page++;load()});pager.append(prev,next);box.appendChild(pager)}
 function renderTasks(rows){const box=$('taskTable');box.textContent='';const rs=rows.map(x=>{const tr=document.createElement('tr');tr.append(cell(x.id),cell(x.type),cell(x.title),cell(x.type==='daily_spin'?'Server-generated':'Not implemented'),cell(x.active?'active':'inactive'));const td=document.createElement('td');td.append(button('Edit',{'editTask':x.id}));tr.append(td);return tr});box.appendChild(table(['ID','Type','Title','Reward engine','State'],rs))}
 function renderEvents(rows){const box=$('eventTable');box.textContent='';const rs=rows.map(x=>{const tr=document.createElement('tr');tr.append(cell(x.id),cell(x.slug),cell(x.title),cell(x.active?'active':'inactive'),cell(x.starts_at||'—'),cell(x.ends_at||'—'));const td=document.createElement('td');td.append(button('Edit',{'editEvent':x.id}));tr.append(td);return tr});box.appendChild(table(['ID','Slug','Title','State','Start','End',''],rs))}
 function renderAudit(rows){const box=$('audit');box.textContent='';const rs=rows.map(x=>{const tr=document.createElement('tr');tr.append(cell(new Date(x.created_at).toLocaleString()),cell(x.action),cell((x.target_type||'')+' '+(x.target_id||'')),cell(x.actor_user_id||''));return tr});box.appendChild(table(['Date','Action','Target','Actor'],rs))}
 async function call(name,args){const {error}=await window.pakcashSupabase.rpc(name,args);if(error)throw error;await load()}
 document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;try{
  if(t.dataset.approve){if(!confirm('Approve withdrawal #'+t.dataset.approve+'? Funds remain reserved until payment.'))return;const notes=$('actionNotes').value.trim();await call('admin_approve_withdrawal',{p_id:Number(t.dataset.approve),p_notes:notes||null})}
  else if(t.dataset.reject){if(!confirm('Reject withdrawal #'+t.dataset.reject+'? It will require a separate refund action.'))return;const notes=$('actionNotes').value.trim();if(notes.length<3){status('Enter a rejection reason in the notes box first.','error');return}await call('admin_reject_withdrawal',{p_id:Number(t.dataset.reject),p_notes:notes})}
  else if(t.dataset.paid){if(!confirm('Mark withdrawal #'+t.dataset.paid+' as paid?'))return;const ref=$('paymentReference').value.trim();if(ref.length<2){status('Enter a payment reference first.','error');return}await call('admin_mark_withdrawal_paid',{p_id:Number(t.dataset.paid),p_payment_reference:ref,p_notes:$('actionNotes').value.trim()||null})}
  else if(t.dataset.refund){if(!confirm('Refund rejected withdrawal #'+t.dataset.refund+'?'))return;await call('admin_refund_withdrawal',{p_id:Number(t.dataset.refund),p_notes:$('actionNotes').value.trim()||null})}
  else if(t.dataset.ref){if(!confirm('Verify referral #'+t.dataset.ref+'?'))return;const reason=$('actionNotes').value.trim();if(reason.length<3){status('Enter a verification reason first.','error');return}await call('admin_verify_referral',{p_referral_id:Number(t.dataset.ref),p_reason:reason})}
  else if(t.dataset.statusSave){const sel=document.querySelector(`[data-status-user="${CSS.escape(t.dataset.statusSave)}"]`);if(!sel)return;if(!confirm('Change account status to '+sel.value+'?'))return;await call('admin_set_user_status',{p_user_id:t.dataset.statusSave,p_status:sel.value})}
  else if(t.dataset.editTask){const x=cache.tasks.find(v=>String(v.id)===t.dataset.editTask);if(x){$('taskId').value=x.id;$('taskType').value=x.type;$('taskTitle').value=x.title;$('taskReward').value=x.reward_pkr;$('taskLimit').value=x.daily_limit;$('taskActive').value=String(x.active);$('taskDescription').value=x.description||'';$('taskConfig').value=JSON.stringify(x.config||{});window.scrollTo({top:$('taskForm').offsetTop,behavior:'smooth'})}}
  else if(t.dataset.editEvent){const x=cache.events.find(v=>String(v.id)===t.dataset.editEvent);if(x){$('eventId').value=x.id;$('eventSlug').value=x.slug;$('eventSlug').readOnly=true;$('eventTitle').value=x.title;$('eventActive').value=String(x.active);$('eventDescription').value=x.description||'';$('eventStarts').value=x.starts_at||'';$('eventEnds').value=x.ends_at||'';$('eventConfig').value=JSON.stringify(x.config||{});window.scrollTo({top:$('eventForm').offsetTop,behavior:'smooth'})}}
 }catch(err){status('Action failed. Please retry.','error')}});
 document.addEventListener('DOMContentLoaded',async()=>{if(!(await guard()))return;$('searchUsers').addEventListener('input',e=>{search=e.target.value.trim();page=0;clearTimeout(window.__search);window.__search=setTimeout(load,350)});$('taskForm').addEventListener('submit',async e=>{e.preventDefault();try{const cfg=JSON.parse($('taskConfig').value||'{}');await call('admin_upsert_task',{p_id:$('taskId').value?Number($('taskId').value):null,p_type:$('taskType').value,p_title:$('taskTitle').value,p_description:$('taskDescription').value,p_reward:Number($('taskReward').value),p_daily_limit:Number($('taskLimit').value),p_active:$('taskActive').value==='true',p_config:cfg,p_event_id:null});e.target.reset();$('taskId').value='';}catch(err){status('Task could not be saved. '+(err.message||''),'error')}});$('eventForm').addEventListener('submit',async e=>{e.preventDefault();try{const cfg=JSON.parse($('eventConfig').value||'{}');await call('admin_set_event',{p_id:$('eventId').value?Number($('eventId').value):null,p_slug:$('eventSlug').value,p_title:$('eventTitle').value,p_description:$('eventDescription').value,p_active:$('eventActive').value==='true',p_starts:$('eventStarts').value||null,p_ends:$('eventEnds').value||null,p_config:cfg});e.target.reset();$('eventId').value='';$('eventSlug').readOnly=false;}catch(err){status('Event could not be saved. '+(err.message||''),'error')}});$('adjustForm').addEventListener('submit',async e=>{e.preventDefault();if(!confirm('Apply this audited wallet adjustment?'))return;try{await call('admin_adjust_wallet',{p_user_id:$('adjustUser').value.trim(),p_amount:Number($('adjustAmount').value),p_reason:$('adjustReason').value.trim()});e.target.reset()}catch(err){status('Adjustment failed. '+(err.message||''),'error')}});load()});
})();
