(function(){
 const q=id=>document.getElementById(id),set=(id,text)=>{const e=q(id);if(e)e.textContent=text};
 function pakDate(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const m=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`}
 function money(n){return `₨${Number(n).toFixed(2)}`}
 function renderTasks(tasks,completedToday){const box=q('taskList');if(!box)return;box.textContent='';if(!tasks.length){const d=document.createElement('div');d.className='empty';d.textContent='No active verified tasks are currently configured.';box.appendChild(d);return}tasks.forEach(t=>{const article=document.createElement('article');article.className='task';const left=document.createElement('div'),h=document.createElement('h3'),p=document.createElement('p'),r=document.createElement('span');h.textContent=t.title;p.textContent=t.description||'';r.className='reward';r.textContent=t.type==='daily_spin'?'Server-generated reward':'';left.append(h,p,r);const b=document.createElement('button');b.className='btn';b.type='button';b.dataset.task=String(t.id);b.dataset.type=t.type;if(completedToday.has(String(t.id))){b.disabled=true;b.textContent='Claimed today';}else{b.textContent='Claim daily spin';}article.append(left,b);box.appendChild(article);});}
 function renderTransactions(rows){const box=q('transactionList');if(!box)return;box.textContent='';if(!rows.length){const d=document.createElement('div');d.className='empty';d.textContent='No wallet transactions yet.';box.appendChild(d);return}const wrap=document.createElement('div');wrap.className='table-wrap';const table=document.createElement('table');table.className='table';table.innerHTML='<thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Available after</th></tr></thead>';const body=document.createElement('tbody');rows.forEach(r=>{const tr=document.createElement('tr');[new Date(r.created_at).toLocaleString(),r.transaction_type,money(r.amount_pkr),money(r.balance_after_pkr)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.appendChild(td)});body.appendChild(tr)});table.appendChild(body);wrap.appendChild(table);box.appendChild(wrap)}
 async function load(){const session=await window.pakcashRequireAuth();if(!session)return;const sb=window.pakcashSupabase;const needProfile=!!q('username')||!!q('referralCode')||!!q('referrals');const needWallet=!!q('balance')||!!q('reserved')||!!q('earned');const needTasks=!!q('taskList');const needTx=!!q('transactionList');const promises=[];if(needProfile)promises.push(sb.from('profiles').select('username,referral_code,verified_referrals,account_status,created_at').eq('id',session.user.id).single());else promises.push(Promise.resolve({data:null,error:null}));if(needWallet)promises.push(sb.from('wallets').select('balance_pkr,reserved_pkr,total_earned_pkr,updated_at').eq('user_id',session.user.id).single());else promises.push(Promise.resolve({data:null,error:null}));if(needTasks)promises.push(sb.from('tasks').select('id,type,title,description,reward_pkr,daily_limit,config').eq('active',true).eq('type','daily_spin').order('id'));else promises.push(Promise.resolve({data:[],error:null}));if(needTx)promises.push(sb.from('wallet_transactions').select('id,transaction_type,amount_pkr,balance_after_pkr,created_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(20));else promises.push(Promise.resolve({data:[],error:null}));const [p,w,t,tx]=await Promise.all(promises);if(p.error||w.error||t.error||tx.error){window.dispatchEvent(new CustomEvent('pakcash:error',{detail:'Account data could not be loaded. Please retry.'}));return}if(p.data){set('username',p.data.username);set('referralCode',p.data.referral_code);set('referrals',p.data.verified_referrals);set('accountStatus',p.data.account_status);if(q('createdAt'))set('createdAt',new Date(p.data.created_at).toLocaleDateString())}if(w.data){set('balance',money(w.data.balance_pkr));set('reserved',money(w.data.reserved_pkr));set('earned',money(w.data.total_earned_pkr))}if(needTasks){const {data:done}=await sb.from('task_completions').select('task_id').eq('user_id',session.user.id).eq('claim_day',pakDate());if(!done)window.dispatchEvent(new CustomEvent('pakcash:error',{detail:'Task history could not be loaded.'}));renderTasks(t.data||[],new Set((done||[]).map(x=>String(x.task_id))))}if(needTx)renderTransactions(tx.data||[]);}
 async function handleTaskClick(e){const b=e.target.closest('[data-task]');if(!b)return;b.disabled=true;try{if(b.dataset.type!=='daily_spin')throw new Error('This task is not rewardable.');const {data,error}=await window.pakcashSupabase.rpc('claim_daily_spin');if(error)throw error;b.textContent='Claimed today';b.disabled=true;set('spinResult',`Reward credited: ${money(data.reward_pkr)}. Next eligible claim: ${new Date(data.next_eligible_at).toLocaleString()}.`);window.dispatchEvent(new CustomEvent('pakcash:success',{detail:`Reward credited: ${money(data.reward_pkr)}`}));await load();}catch(err){b.disabled=false;window.dispatchEvent(new CustomEvent('pakcash:error',{detail:'The task could not be completed. Please try again.'}));}}
 document.addEventListener('DOMContentLoaded',()=>{const box=q('taskList');if(box)box.addEventListener('click',handleTaskClick);if(document.body.dataset.private==='true')load()});
 function referralUrl(code){const u=new URL('/events/index.html',location.origin);u.searchParams.set('ref',code);return u.toString()}
 window.pakcashCopyReferral=async function(){const p=await window.pakcashGetProfile();if(!p)return;const url=referralUrl(p.referral_code);try{await navigator.clipboard.writeText(url);window.dispatchEvent(new CustomEvent('pakcash:success',{detail:'Referral link copied.'}));}catch{window.dispatchEvent(new CustomEvent('pakcash:error',{detail:'Copy is unavailable in this browser. You can copy the link manually.'}));}}
 window.pakcashShareReferral=async function(){const p=await window.pakcashGetProfile();if(!p)return;const url=referralUrl(p.referral_code),text=`🇵🇰 Discover PakCash events: ${url}`;try{if(navigator.share){await navigator.share({title:'PakCash',text,url});}else{window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank','noopener,noreferrer');}}catch(e){if(e.name!=='AbortError')window.dispatchEvent(new CustomEvent('pakcash:error',{detail:'Sharing was not completed.'}));}}
})();